### ISSUE TITLE
feat: 플래너 페이지 API 구현

### ISSUE THREAD

**Issue by chrisheo** [KUALSNS/BE#37]
**Feature Request**
기능 설명 : 글 플래너 페이지에 필요한 API 기능 구현

**To-Do List**
- [ ] 성장 데이터 확인 기능
- [x] 달성한 챌린지, 캘린더 아이콘 확인 기능
- [x] 챌린지 기록 확인 기능
